name: Build and push on main
on:
  push:
    branches:
      - main

jobs:
  check-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: npm install

      - name: Check format
        run: npm run format-check

      - name: Check lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Audit
        run: npm audit
      
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
      
      - name: Trigger build
        env:
          CLOUDFLARE_PAGE_TRIGGER_DEPLOYMENT: ${{ secrets.CLOUDFLARE_PAGE_TRIGGER_DEPLOYMENT }}
        run: curl -X POST "$CLOUDFLARE_PAGE_TRIGGER_DEPLOYMENT"
